
  server:
    servlet:
      context-path: /ge-music
    port: 8081

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/ge_music
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:static/mapper/*.xml
    configuration:
     map-underscore-to-camel-case: true


  logging:
    level:
     ces.ge.music.mapper: debug